package com.eventsourcing.commerce.eventStore;

public enum EventType {
    CART_CREATED,
    PRODUCT_ADDED_IN_CART,
    PRODUCT_REMOVED_FROM_CART,
    CART_ITEM_EXPIRED,
    PRODUCT_UPDATED_IN_CART,
    PRODUCT_REGISTERED,
    STOCK_ADDED,
    STOCK_RESERVED,
    STOCK_DEDUCTED,
    STOCK_RELEASED,
    PRODUCT_UPDATED,
    PRODUCT_DISCONTINUED,
    CLIENT_REGISTERED,
    CLIENT_DEACTIVATED,
    CLIENT_UPDATED,
    ORDER_PLACED,
    ORDER_PAID,
    ORDER_CANCELED
}
